spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ziphub
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  token:
    secretKey: ziphub
    expiredMs: 86400000

gcp:
  config:
    file: gcp-account-file.json
  project:
    id: imposing-pipe-356718
  bucket:
    id: media-bucket-007
  dir:
    name: dev